site_name: Codeburner
site_url: http://groupon.github.io/codeburner
site_description: One static analysis tool to rule them all...
site_author: Groupon, Inc.
site_favicon: favicon.ico
repo_url: https://github.com/groupon/codeburner
extra_css:
  - css/prism.css
extra_javascript:
  - js/prism.js
pages:
  - Home: index.md
  - Setup Guide:
    - Quick Start: setup/quickstart.md
    - Installation: setup/installation.md
    - Configuration: setup/configuration.md
    - Scanning Tools: setup/scanning_tools.md
    - Start Burning!: setup/startup.md
  - User Guide:
    - Submit a Burn: user/burns.md
    - Interact with Findings: user/findings.md
    - Filtering: user/filters.md
    - Statistics/Charts: user/stats.md
  - Developer Guide:
    - Rails Backend: developer/backend.md
    - Web Client: developer/client.md
    - Pipeline: developer/pipeline.md
    - API Reference: developer/api.md
markdown_extensions:
  - toc:
      permalink: '#'
  - admonition
  - codehilite(css_class=code)
theme_dir: ./docs/theme
extra:
  logo: images/fire.png
  author:
    github: groupon
    twitter: GrouponEng
