#
#The MIT License (MIT)
#
#Copyright (c) 2016, Groupon, Inc.
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
#
github:
  api_endpoint: https://api.github.com/
  api_access_token: my_github_api_token
  link_host: https://www.github.com
jira:
  username: my_jira_user
  password: my_jira_password
  host: https://my_jira_host
  context_path: ''
  use_ssl: false
  link_host: https://my_jira_host
mail:
  from: '"Codeburner" <codeburner@mydomain.com>'
  link_host:
    development: localhost:9000
    staging: my_staging_host
    production: my_production_host
    test: localhost:9000
pipeline:
  npm_registry: https://registry.npmjs.org/
  tasks_for:
    Ruby:
      - BundleAudit
      - Brakeman
      - Dawnscanner
    JavaScript:
      - RetireJS
      - NodeSecurityProject
    CoffeeScript:
      - RetireJS
      - NodeSecurityProject
    Java:
      - PMD
      - FindSecurityBugs
  pmd_path: /pmd/pmd-bin-5.4.1
  findsecbugs_path: /findsecbugs
  checkmarx_server: my_checkmarx_server
  checkmarx_user: my_checkmarx_user
  checkmarx_password: my_checkmarx_password
  checkmarx_log: my_checkmarx_logfile
